apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-linkat-passwd"
spec:
  kprobes:
  - call: "sys_linkat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    - index: 3
      type: "string"
    - index: 4
      type: "int"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/etc/passwd"
        - "/etc/bashrc"
        - "/etc/host.conf"
        - "/etc/hostname"
        - "/etc/hosts"
        - "/etc/profile"
        - "/etc/resolv.conf"
        - "/etc/services"
      matchActions:
      - action: Sigkill
