apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-accept"
spec:
  kprobes:
  - call: "sys_accept"
    syscall: true
    args:
    - index: 0
      type: int
    - index: 1 
      type: "sock"
    - index: 2  
      type: int
    selectors:
    - matchArgs:
      - index: 1
        operator: "DPort"
        values:
         - "22"
      matchActions:
      - action: Override
        argError: -1
